server {
    listen 8080;
    root /usr/share/nginx/html;

    gzip_static on;

    types {
        application/wasm wasm;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(?:wasm|dll|dat|blat|js|css)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    location = /index.html {
        add_header Cache-Control "no-cache";
    }

    location = /service-worker.js {
        add_header Cache-Control "no-cache";
    }
}
