server {
    listen 8080;
    root /usr/share/nginx/html;

    gzip_static on;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* ^/_framework/.+\.(?:wasm|dll|dat|blat|js)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    location ~* \.(?:js|css|json|webmanifest|png)$ {
        add_header Cache-Control "no-cache";
    }

    location = /manifest.webmanifest {
        default_type application/manifest+json;
    }

    location = /index.html {
        add_header Cache-Control "no-cache";
    }
}
