<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\shared\PSPad.Abstractions\PSPad.Abstractions.csproj" />
    <ProjectReference Include="..\PSPad.Module.Tasks\PSPad.Module.Tasks.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="PSPad.Module.Sharing.Tests" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
